#!/bin/bash

echo "🚀 Deploy Latest Backend to Production"
echo "========================================"
echo ""
echo "Your production server is missing the stocking routes."
echo "You need to deploy the latest code."
echo ""

# Check if we're in the right directory
if [ ! -f "server/index.js" ]; then
    echo "❌ Error: Run this script from the project root directory"
    exit 1
fi

echo "📋 Steps to deploy to your production server:"
echo ""
echo "1️⃣  SSH into your production server:"
echo "    ssh username@kisumu.codewithseth.co.ke"
echo ""
echo "2️⃣  Navigate to your app directory:"
echo "    cd /path/to/your/stayfresh/server"
echo ""
echo "3️⃣  Pull latest code:"
echo "    git pull origin main"
echo ""
echo "4️⃣  Install any new dependencies:"
echo "    npm install"
echo ""
echo "5️⃣  Restart the server:"
echo "    # If using PM2:"
echo "    pm2 restart stayfresh"
echo "    # Or if using systemd:"
echo "    sudo systemctl restart stayfresh"
echo "    # Or if using screen/tmux:"
echo "    # Kill the old process and start again:"
echo "    node index.js"
echo ""
echo "6️⃣  Verify deployment:"
echo "    curl https://www.kisumu.codewithseth.co.ke/api/health"
echo "    curl -I https://www.kisumu.codewithseth.co.ke/api/stocking/book"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Quick Verification:"
echo "After deploying, the stocking route should return:"
echo "  - 401 Unauthorized (if no token) ✅ Good!"
echo "  - 404 Not Found ❌ Route still missing"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Alternative: Push code to production"
echo ""
echo "If you want to push from here:"
echo "  git add ."
echo "  git commit -m 'Add stocking routes'"
echo "  git push origin main"
echo ""
echo "Then SSH to server and pull the changes."
echo ""
